import type { Metadata } from "next";
import Sidebar from "../components/Sidebar";


export const metadata: Metadata = {
    title: "Instagram",
    description: "Generated by create next app",
    icons: {
        icon: "./icon.png"
    }
};

export default async function RootLayout({ children, }: { children: React.ReactNode }) {

    return (
        <div className='flex'>
            <Sidebar />
            <div className="flex-1 py-10">
                {children}
            </div>
        </div>
    );
}
