import type { Metadata } from "next";
import Sidebar from "../components/Sidebar";


export const metadata: Metadata = {
    title: "Instagram",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div>
            <div className='flex'>
                <Sidebar />
                <div className="w-full">
                    {children}
                </div>
            </div>
        </div>
    );
}
