import type { Metadata } from "next";
import { Suspense } from "react";
import { redirect } from 'next/navigation'
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = cookies().get('token_auth')
  if (token) {
    redirect('/')
  }
  return (
    <div>
      <Suspense fallback={<h1>loading</h1>} >
        {children}
      </Suspense>
    </div>
  );
}
