import type { Metadata } from "next";
import UserInfo from "./components/UserInfo";
import { Params } from "next/dist/shared/lib/router/utils/route-matcher";


export const metadata: Metadata = {
    title: "Instagram",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    params
}: {
    children: React.ReactNode,
    params: Params
}) {
    return (
        <div className='lg:flex justify-center'>
            <div className='lg:w-[900px]'>
                <div className="sm:px-3">
                    <UserInfo params={params} />
                    {children}
                </div>
            </div>
        </div>
    );
}
