import type { Metadata } from "next";
import ProfileHeader from "./components/ProfileHeader";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Instagram",
    description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: { children: React.ReactNode, params: { userId: string } }) {
    const { userId } = params;
    const fetchUser = async () => {
        try {
            if (userId.length != 24) redirect('/')
            const res = await fetch(`${process.env.BASE_URL}/api/user/user-info?userId=${userId}`, {
                method: 'GET',
            });
            if (!res.ok) {
                throw new Error(await res.text());
            }
            return await res.json();
        } catch (error) {
            console.error(error);
        }
    }

    const data = await fetchUser();
    return (
        <div className='lg:flex justify-center'>
            <div className='lg:w-[900px]'>
                <div className="sm:px-3">
                    <ProfileHeader data={data} />
                    {children}
                </div>
            </div>
        </div>
    );
}
